# Generated by Django 2.0.10 on 2019-02-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_auto_20190201_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='admin',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writer',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
