# Generated by Django 2.0.10 on 2019-02-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_auto_20190201_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='phonenumber',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
