# Generated by Django 2.0.10 on 2019-02-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_auto_20190201_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
